# Lenguanjes de Programación
### Universidad Politecnica Salesiana
### Ingeniería en Ciencias de la Computación
### Programación

<img src="../assets/ups-icc.png" alt="Logo Carrera" style="height:75px;"/>


---

## Autores del Material
- **Instructor**: Ing. Pablo Torres
- **Contacto**: ptorresp@ups.edu.ec

---

## A. Tema: Matrices en Python

### Descripción General
En este tema, aprenderemos sobre las **matrices** en Python, que son estructuras de datos bidimensionales utilizadas para almacenar y manipular datos de manera organizada. Exploraremos cómo crear matrices utilizando listas de listas y la biblioteca **NumPy**, acceder y modificar sus elementos, realizar operaciones básicas como suma y multiplicación, y aplicar métodos avanzados para análisis de datos.

### Objetivos de Aprendizaje
- Comprender qué son las matrices en Python y sus aplicaciones.
- Aprender a crear y asignar matrices utilizando listas de listas y NumPy.
- Acceder y modificar elementos de una matriz utilizando índices.
- Realizar operaciones básicas con matrices, como suma, multiplicación y transposición.
- Utilizar métodos incorporados y funciones de NumPy para manipular y analizar matrices.
- Iterar sobre los elementos de una matriz utilizando bucles.
- Aplicar buenas prácticas en el manejo de matrices para escribir código eficiente y legible.

---

### 1. Introducción a las Matrices

Las **matrices** en Python son estructuras de datos bidimensionales que permiten almacenar colecciones de elementos organizados en filas y columnas. Se pueden representar utilizando listas de listas o, de manera más eficiente, mediante la biblioteca **NumPy**.

#### 1.1. Creación de Matrices con Listas de Listas

Puedes crear matrices utilizando listas anidadas (listas dentro de listas):

```python
# Matriz 2x3 (2 filas, 3 columnas)
matriz = [
    [1, 2, 3],
    [4, 5, 6]
]

print(matriz)
# Output: [[1, 2, 3], [4, 5, 6]]
```

In [3]:
matriz = [[1,False,3],[4,5,True]]
print(matriz)

[[1, False, 3], [4, 5, True]]


#### 1.2. Creación de Matrices con NumPy

**NumPy** es una biblioteca poderosa para el manejo de arreglos multidimensionales en Python. Es altamente recomendada para trabajar con matrices debido a su eficiencia y funcionalidad.

Primero, asegúrate de tener NumPy instalado. Si no lo tienes, puedes instalarlo usando `pip`:

```bash
pip install numpy
```

Luego, puedes crear matrices de la siguiente manera:

```python
import numpy as np

# Matriz 2x3 utilizando NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matriz_np)
# Output:
# [[1 2 3]
#  [4 5 6]]
```

---

In [3]:
import numpy as np
print(np.__version__)

matriz_np = np.array([
    [1,2,3],
    [4,5,6]
    ])
print(matriz_np)

2.2.2
[[1 2 3]
 [4 5 6]]


In [13]:
matriz=[[1, False, 3], [[8, 9, 7], 5, True]]
print(matriz)
print(matriz[1][0][1])


[[1, False, 3], [[8, 9, 7], 5, True]]
9


### 2. Acceso y Modificación de Elementos en una Matriz

#### 2.1. Acceder a Elementos

Cada elemento en una matriz puede ser accedido mediante su índice de fila y columna. En Python, los índices comienzan en `0`.

##### Con Listas de Listas

```python
matriz = [
    [1, 2, 3],
    [4, 5, 6]
]

# Acceder al elemento en la primera fila, segunda columna
elemento = matriz[0][1]
print(elemento)  # Output: 2
```

#### Con NumPy

```python
import numpy as np

matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Acceder al elemento en la primera fila, segunda columna
elemento = matriz_np[0, 1]
print(elemento)  # Output: 2

```

#### 2.2. Modificar Elementos

##### Con Listas de Listas

```python
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# Modificar el elemento en la segunda fila, tercera columna
print(matriz)
# Output: [[1, 2, 3],[4, 5, 9],[7, 8, 10]]

```

#### Con NumPy

```python
import numpy as np

matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Modificar el elemento en la segunda fila, tercera columna
matriz_np[1, 2] = 10
print(matriz_np)
# Output:
# [[ 1  2  3]
#  [ 4  5 10]]


```

---

## 3. Operaciones Básicas con Matrices

#### 3.1. Suma de Matrices

##### Con Listas de Listas


```python
matriz1 = [
    [1, 2],
    [3, 4]
]

matriz2 = [
    [5, 6],
    [7, 8]
]

# Suma de matrices
suma = []
for i in range(len(matriz1)):
    fila = []
    for j in range(len(matriz1[0])):
        fila.append(matriz1[i][j] + matriz2[i][j])
    suma.append(fila)

print(suma)
```
```
Output: [[6, 8], [10, 12]]
```


In [25]:
matriz1 = [
    [1, 2],
    [3, 4]
]

matriz2 = [
    [5, 6],
    [7, 8]
]

# Suma de matrices
suma = []
for i in range(len(matriz1)):
    fila = []
    for j in range(len(matriz1[0])):
        fila.append(matriz1[i][j] + matriz2[i][j])
    suma.append(fila)

print(suma)


[[6, 8], [10, 12]]


#### Con NumPy

```python
import numpy as np

matriz1 = np.array([
    [1, 2],
    [3, 4]
])

matriz2 = np.array([
    [5, 6],
    [7, 8]
])

suma = matriz1 + matriz2
print(suma)
# Output:
# [[ 6  8]
#  [10 12]]

```

#### 3.2. Multiplicación de Matrices

##### Producto Elemento a Elemento

##### Con Listas de Listas

```python
matriz1 = [
    [1, 2],
    [3, 4]
]

matriz2 = [
    [5, 6],
    [7, 8]
]

# Multiplicación elemento a elemento
producto = []
for i in range(len(matriz1)):
    fila = []
    for j in range(len(matriz1[0])):
        fila.append(matriz1[i][j] * matriz2[i][j])
    producto.append(fila)

print(producto)
# Output: [[5, 12], [21, 32]]
```

##### Con NumPy

```python
import numpy as np

matriz1 = np.array([
    [1, 2],
    [3, 4]
])

matriz2 = np.array([
    [5, 6],
    [7, 8]
])

producto = matriz1 * matriz2
print(producto)


```
```

Output:
[[ 5 12]
[21 32]]
```


#### Producto de Matrices (Multiplicación de Matrices)

##### Con Listas de Listas

```python
matriz1 = [
    [1, 2, 3],
    [4, 5, 6]
]

matriz2 = [
    [7, 8],
    [9, 10],
    [11, 12]
]

# Inicializar la matriz resultado con ceros
resultado = [
    [0, 0],
    [0, 0]
]

# Realizar la multiplicación
for i in range(len(matriz1)):
    for j in range(len(matriz2[0])):
        for k in range(len(matriz2)):
            resultado[i][j] += matriz1[i][k] * matriz2[k][j]

print(resultado)
# Output: [[58, 64], [139, 154]]

```

##### Con NumPy

```python
import numpy as np

matriz1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matriz2 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

resultado = np.dot(matriz1, matriz2)
print(resultado)

```

```
 Output:
 [[ 58  64]
  [139 154]]
```

### 3.3. Transposición de Matrices

#### Con Listas de Listas

```python
matriz = [
    [1, 2, 3],
    [4, 5, 6]
# 

# Transponer la matriz
transpuesta = []
for j in range(len(matriz[0])):
    fila = []
    for i in range(len(matriz)):
        fila.append(matriz[i][j])
    transpuesta.append(fila)

print(transpuesta)

```

```

Output: [[1, 4], [2, 5], [3, 6]]
```

#### Con NumPy

```python
import numpy as np

matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transpuesta = matriz.T
print(transpuesta)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


```

---

### 4. Uso de NumPy para Matrices

#### 4.1. Creación y Manipulación de Matrices con NumPy

NumPy proporciona funciones avanzadas para crear y manipular matrices de manera eficiente.

```python
import numpy as np

# Crear una matriz de ceros de 3x3
ceros = np.zeros((3, 3))
print("Matriz de ceros:\n", ceros)

# Crear una matriz de unos de 2x4
unos = np.ones((2, 4))
print("\nMatriz de unos:\n", unos)

# Crear una matriz de números aleatorios de 3x3
aleatorios = np.random.rand(3, 3)
print("\nMatriz de números aleatorios:\n", aleatorios)
```

---

### 5. Iteración sobre Matrices

Puedes **iterar** sobre las filas y columnas de una matriz utilizando bucles `for`.

#### 5.1. Iterar sobre Filas

##### Con Listas de Listas

```python
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Iterar sobre cada fila
for fila in matriz:
    print(fila)

# Output:
# [1, 2, 3]
# [4, 5, 6]
# [7, 8, 9]
```

In [ ]:
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)
for fila in matriz:
    # print(fila)
    for elemento in fila:
        print(elemento)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
1
2
3
4
5
6
7
8
9


In [24]:
matriz = [
    [1, 2, 3],
    [4, 5, 6,11,2],
    [7, 8, 9],
    [7, 8, 9,4]
]
for f in range(len(matriz)):
    print(f"Fila -> {f}" )
    for c in range(len(matriz[f])):
        print(c)

Fila -> 0
0
1
2
Fila -> 1
0
1
2
3
4
Fila -> 2
0
1
2
Fila -> 3
0
1
2
3


#### Con NumPy

```python

import numpy as np

matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Iterar sobre cada fila
for fila in matriz_np:
    print(fila)
    
```
```

 Output:
 [1 2 3]
 [4 5 6]
 [7 8 9]
 
```

#### 5.2. Iterar sobre Elementos Individuales

##### Con Listas de Listas

```python
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Iterar sobre cada elemento
for i in range(len(matriz)):
    for j in range(len(matriz[0])):
        print(f"Elemento en posición [{i}][{j}]: {matriz[i][j]}")
        
        
```


#### Con NumPy

```python
import numpy as np

matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Iterar sobre cada elemento
for i in range(matriz_np.shape[0]):
    for j in range(matriz_np.shape[1]):
        print(f"Elemento en posición [{i}][{j}]: {matriz_np[i, j]}")
        
        
```

---

### 6. Comprensión de Matrices (List Comprehensions)

La **comprensión de matrices** es una forma concisa de crear matrices basadas en iteraciones y condiciones.

```python
# Crear una matriz de 3x3 con ceros
ceros = [[0 for _ in range(3)] for _ in range(3)]
print(ceros)
# Output: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# Crear una matriz de identidad 3x3
identidad = [[1 if i == j else 0 for j in range(3)] for i in range(3)]
print(identidad)
# Output: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
```

---

## **Conclusión**

Las **matrices** son estructuras de datos fundamentales en Python para almacenar y manipular datos bidimensionales. Entender cómo trabajar con matrices utilizando listas de listas y NumPy es esencial para desarrollar programas eficientes y realizar análisis de datos complejos. La biblioteca NumPy, en particular, ofrece herramientas avanzadas que facilitan el manejo de matrices, mejorando significativamente la eficiencia y la funcionalidad de tus programas.

**Recomendaciones para los Estudiantes:**

- **Practicar la Creación de Matrices**: Intenta crear matrices de diferentes tamaños y tipos de datos para familiarizarte con su estructura.

- **Realizar Operaciones Variadas**: Implementa operaciones básicas y avanzadas como suma, multiplicación, transposición y búsqueda de elementos para fortalecer tu comprensión.

- **Explorar NumPy**: Profundiza en el uso de NumPy para aprovechar al máximo sus funcionalidades avanzadas en el manejo de matrices.

- **Resolver Ejercicios Prácticos**: Completa los ejercicios propuestos y busca otros adicionales para aplicar tus conocimientos en situaciones reales.

- **Leer la Documentación**: Consulta la documentación oficial de NumPy para conocer todas las funciones y métodos disponibles para el manejo de matrices.

